swagger: '2.0'
schemes:
  - https
host: moneybird.com
basePath: /api/v1

info:
  description: |
    # Introduction

    Moneybird API Client for PHP

    ## Requirements
    To use the Moneybird API client, the following things are required:
    + Get yourself a Moneybird account. [Can be done here!](https://www.moneybird.nl/aanmelden/)
    + Create a personal access token. [Can be done here!](https://moneybird.com/user/applications/new)
    + Get your administration id.

    ## Getting started

    Requiring the included autoloader. If you're using Composer, you can skip this step.

    ```php
    require "Moneybird/Autoloader.php";
    ```

    Initializing the Moneybird API client, and setting your access key and administration id.

    ```php
    $moneybirdClient = new Client;
    $moneybirdClient->setAccessToken("YOUR_ACCESS_TOKEN")
                    ->setAdministrationID("YOUR_ADMINISTRATION_ID");
    ```

  version: 1.0.0
  title:     Moneybird API Client for PHP
  contact:
    email: t.bokdam@seronaris.nl
    url: 'https://github.com/TriPss'

  license:
    name: MIT
    url: 'https://github.com/TriPSs/Moneybird-API/blob/master/LICENSE'

  x-logo:
    url: https://www.moneybird.nl/data/share/moneybird-85febefd.png

produces:
  - application/json

consumes:
  - application/json

x-tagGroups:
  - name: Routes
    tags:
      - Sales Invoices

tags:
  - name: Sales Invoices
